### ISSUE TITLE
Could not writeJwtFile JWT AX6gZoFhIJ7EnZVsvELdto storage path

### ISSUE THREAD

**Issue by songdechao** [cloudogu/sonar-cas-plugin#42]
java.nio.file.AccessDeniedException: /opt/session/ST-d0mrKKg5oCBINRvqalc8jialVlpwqA90QXo1WlOvcJ0=
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at java.base/java.nio.file.Files.write(Files.java:3422)
        at org.sonar.plugins.cas.session.SessionFileHandler.createServiceTicketFile(SessionFileHandler.java:70)
        at org.sonar.plugins.cas.session.FileSessionStore.store(FileSessionStore.java:48)
        at org.sonar.plugins.cas.LoginHandler.handleLogin(LoginHandler.java:92)
        at org.sonar.plugins.cas.CasIdentityProvider.init(CasIdentityProvider.java:69)
        at org.sonar.server.authentication.InitFilter.handleBaseIdentityProvider(InitFilter.java:106)
        at org.sonar.server.authentication.InitFilter.handleProvider(InitFilter.java:80)
        at org.sonar.server.authentication.InitFilter.doFilter(InitFilter.java:73)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)

**Comment by cbeyer42** [comment]
Hello songdechao,

it seems you don't have the right permissions to write the JWT to `/opt/session`. If you want to use another location for you sessions you can configure it inside the file `sonar.properties`:

```
sonar.cas.sessionStorePath=/path/to/your/sessionstore
```

I hope this will help you.

**Comment by songdechao** [comment]
it‘s needs permissions
